### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by onayem** [zueve/django-rest-captcha#6]
We are using this package frequently, but here is the dependency issue we recently face:

We wanted to upgrade our project's Python version to 3.9.0. 
Pillow package supports Python 3.9.0 with the version `Pillow==8.0`.
`django-rest-captcha` does not have any problems with Python 3.9.0 but it depends on `Pillow` package and versions are restricted to `Pillow<5.0.0`, `Pillow>=4.1.1`.

`pip` used to print this warning but still install the packages. New 2020-resolver of `pip`, which is released a few days ago, does not allow this anymore. Therefore, we will not be able to use `django-rest-captcha` if we upgrade our Python version.

My solution suggestion is that: Can you enlarge or remove the restriction of the `Pillow` package dependency?
Thank you.

**Comment by zueve** [comment]
Please check, new version submitted

**Comment by onayem** [comment]
It works now! Thank you very much!
