### ISSUE TITLE
Invalid or expired captcha key

### ISSUE THREAD

**Issue by MIRAMAXED** [zueve/django-rest-captcha#8]
Hi! I have a problem with validation of the captcha. 
Here I requested captcha:
![image](https://user-images.githubusercontent.com/5852641/103244615-4222c980-4966-11eb-9a3a-9f67bfe8b191.png)
Here I POST data with the captcha's key and value: 
![image](https://user-images.githubusercontent.com/5852641/103244653-56ff5d00-4966-11eb-8a95-9c158ba35bb9.png)
In result, I have an error:
![image](https://user-images.githubusercontent.com/5852641/103244725-9a59cb80-4966-11eb-8fce-806a4450595f.png)
![image](https://user-images.githubusercontent.com/5852641/103244598-31725380-4966-11eb-9560-ad60ed6b8429.png)

The difference between requests is about few seconds!
What I do wrong?

**Comment by MIRAMAXED** [comment]
The problem was in the cache settings ¯\_(ツ)_/¯

**Comment by nguyenhuutinh** [comment]
how did you resolve this issue @MIRAMAXED

**Comment by MIRAMAXED** [comment]
@nguyenhuutinh The CACHE setting solved my problem
```python
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
    }
}
```
